package com.certimaster.common_library.event;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Event published when an exam session is started.
 * Sent from exam-service to result-service via Kafka.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ExamSessionStartedEvent implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * Unique session ID generated by exam-service.
     */
    private Long sessionId;

    /**
     * User ID from auth-service.
     */
    private Long userId;

    /**
     * Username for display.
     */
    private String username;

    /**
     * Exam ID.
     */
    private Long examId;

    /**
     * Exam title.
     */
    private String examTitle;

    /**
     * Certification ID.
     */
    private Long certificationId;

    /**
     * Certification name.
     */
    private String certificationName;

    /**
     * Exam mode: PRACTICE, EXAM, REVIEW.
     */
    private String mode;

    /**
     * Total number of questions in this session.
     */
    private Integer totalQuestions;

    /**
     * Duration in minutes.
     */
    private Integer durationMinutes;

    /**
     * Passing score percentage.
     */
    private Integer passingScore;

    /**
     * Session start time.
     */
    private LocalDateTime startTime;

    /**
     * Event timestamp.
     */
    @Builder.Default
    private LocalDateTime eventTime = LocalDateTime.now();
}
