package com.certimaster.common_library.event;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serial;
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

/**
 * Response containing exam results.
 * Sent from result-service back to exam-service via Kafka reply pattern.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ExamResultResponse implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    /**
     * Result ID generated by result-service.
     */
    private Long resultId;

    /**
     * Session ID from exam-service.
     */
    private Long sessionId;

    /**
     * User ID.
     */
    private Long userId;

    /**
     * Exam ID.
     */
    private Long examId;

    /**
     * Exam title.
     */
    private String examTitle;

    /**
     * Total number of questions.
     */
    private Integer totalQuestions;

    /**
     * Number of correct answers.
     */
    private Integer correctAnswers;

    /**
     * Number of wrong answers.
     */
    private Integer wrongAnswers;

    /**
     * Number of unanswered questions.
     */
    private Integer unanswered;

    /**
     * Raw score (number of correct answers).
     */
    private BigDecimal score;

    /**
     * Score percentage.
     */
    private BigDecimal percentage;

    /**
     * Pass/fail status (PASSED or FAILED).
     */
    private String passStatus;

    /**
     * Passing score percentage required.
     */
    private Integer passingScore;

    /**
     * Total time taken in seconds.
     */
    private Integer timeTakenSeconds;

    /**
     * When the exam was completed.
     */
    private LocalDateTime completedAt;

    /**
     * Topic-wise performance breakdown.
     */
    private List<TopicPerformanceData> topicPerformances;

    /**
     * Per-question results with explanations.
     */
    private List<QuestionResultData> questionResults;

    /**
     * Whether result calculation was successful.
     */
    private boolean success;

    /**
     * Error message if calculation failed.
     */
    private String errorMessage;

    /**
     * Topic performance data.
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class TopicPerformanceData implements Serializable {

        @Serial
        private static final long serialVersionUID = 1L;

        /**
         * Topic ID.
         */
        private Long topicId;

        /**
         * Topic name.
         */
        private String topicName;

        /**
         * Total questions in this topic.
         */
        private Integer totalQuestions;

        /**
         * Correct answers in this topic.
         */
        private Integer correctAnswers;

        /**
         * Performance percentage for this topic.
         */
        private BigDecimal percentage;
    }

    /**
     * Per-question result data.
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class QuestionResultData implements Serializable {

        @Serial
        private static final long serialVersionUID = 1L;

        /**
         * Question ID.
         */
        private Long questionId;

        /**
         * Question text.
         */
        private String questionText;

        /**
         * User's selected answer IDs.
         */
        private Long[] userAnswerIds;

        /**
         * Correct answer IDs.
         */
        private Long[] correctAnswerIds;

        /**
         * Whether the answer was correct.
         */
        private Boolean isCorrect;

        /**
         * Time spent on this question in seconds.
         */
        private Integer timeSpentSeconds;

        /**
         * Explanation for the correct answer.
         */
        private String explanation;

        /**
         * Reference material for further study.
         */
        private String reference;
    }
}
