package com.certimaster.common_library.event;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serial;
import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Reply event when exam session is created.
 * Sent from result-service back to exam-service via Kafka.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ExamSessionCreatedEvent implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    /**
     * Created session ID (generated by database).
     */
    private Long sessionId;

    /**
     * User ID.
     */
    private Long userId;

    /**
     * Exam ID.
     */
    private Long examId;

    /**
     * Whether creation was successful.
     */
    private boolean success;

    /**
     * Error message if creation failed.
     */
    private String errorMessage;

    /**
     * Event timestamp.
     */
    @Builder.Default
    private LocalDateTime eventTime = LocalDateTime.now();
}
